### ISSUE TITLE
Can I use segment-liftover in conversion of coordinates cross-sepecies?

### ISSUE THREAD

**Issue by madzafv** [baudisgroup/segment-liftover#2]
Hi!
I have a still unpublished genome assembly, which I used to map and annotate my DNA-Seq pop data.
I want to use the ref genome for the zebra finch available from ensembl as my ancestral ref in some pop gen analysis. For this, I would have to convert the coordinates from  the zebra finch available from ensembl to mine unpublished one.
Does this program fits to my problem?
Or would you recomend any other tool that would?
Thanks!

**Comment by KyleGao** [comment]
Sorry, I think this program does not fit your need.
For what I know, all existing conversion tools rely on mapping files. Since your genome is unpublished, you have to build your own mapping file, which is not an easy task. 
An alternative I can think of could be to convert zebra finch to another species that is very close to yours, then do some alignment analysis in the region of interest.
