### ISSUE TITLE
unconverted.log

### ISSUE THREAD

**Issue by mdeloger** [baudisgroup/segment-liftover#3]
Hi @KyleGao ,

Is there a way to understand why a segment was not converted and if in some way a fine-tuning of a parameter may overcome this unconversion, please ?

For example an hg19 to hg38 conversion gave me : 

chromosome	start	end	same_chr/new_chr	length_ratio/new_pos	file
chr1	144854271	152052338	True	0.4237	input_dir/GE2486-Tumor_subclonal_allele_spe_cnv_0.43cellularity_2ploidy.transformed.txt
chr1	144621642	153916821	True	3.6042	input_dir/GE3344-Tumor_subclonal_allele_spe_cnv_0.55cellularity_2ploidy.transformed.txt

Thank you in advance for your help

**Comment by KyleGao** [comment]
Use the option `--beta 4`, this should solve your problem.

These segments were excluded because of their dramatic change in length, shown as the length_ratio 0.4237 and 3.6042. 
This filtering is controlled by parameter beta:  
`--beta FLOAT                    Parameter in quality control.`
The default value is 2 and the condition is:
1/beta < length(original segment)/length(new segment) < beta

**Comment by mdeloger** [comment]
Oh ok, I will try :-)
Thank you very much for your explanation.

Best regards
