### ISSUE TITLE
Only first file output name in batch mode

### ISSUE THREAD

**Issue by stardustcx** [baudisgroup/segment-liftover#4]
Dear Prof.
I found a bug when I run segment_liftover in batch mode. It just output one file which got the first file's name , but hold the last file's output. It is caused by a logic error in segmentLiftover.py near line 960 that the "if segment_output_file == None" statement only pass at first time. I hope you can fix this in furture version. Thanks.

J Yang

**Comment by KyleGao** [comment]
Thank you Yang! Could you please kindly provide us with your parameters and file structures, so that we can reproduce the problem precisely?

**Comment by stardustcx** [comment]
I put two segmentation files in cbs_hg17  (eg. one named a.txt and another named b.xls; both are tab-delimited files) in a directory, and I ran the following command:
segment_liftover -i cbs_hg17 -o cbs_hg19 -c hg17ToHg19.over.chain -si ".*(xls|txt)"
The resultant cbs_hg19 directory will only have converted a.txt but with the content of converted b.xls.
I have fixed this by may self:

if (segment_input_file !=None) and  (seg_pattern.match(os.path.basename(f))):
                segment_output_file_bak=segment_output_file # make a backup of the original name
                if segment_output_file == None:
                    segment_output_file = seg_pattern.match(os.path.basename(f)).group(0)
                segment_out_path = os.path.join(output_dir, rel_path, segment_output_file)
                segment_output_file=segment_output_file_bak # recover to original name

**Comment by KyleGao** [comment]
This is an interesting bug. It doesn't behave as we intended. I guess we also didn't explain clearly, so there is a bit misunderstanding of the expected file structure.

In general, the tool expects only one segment file in each directory, because segment files often have the same file name (i.e. generated from the same pipeline and all called segments.tsv). The most common structure is like this: 
GSE0123/GSM012345/segments.tsv
GSE0123/GSM012346/segments.tsv 
...

When you have more than one file in one directory, you can use --index_file FILE.
The tool will directly process the files you specified in FILE without directory traversing.
In your case, the index file should look like this:
cbs_hg17/a.txt
cbs_hg17/b.xls
And the command:
segment_liftover -i cbs_hg17 -o cbs_hg19 -c hg17ToHg19.over.chain -x your_index_file

However, if you have a number of directories which all contain 2 files. I would recommend running the tool twice, each time converting one file. 

Thank you again for the information, we will look into this bug more thoughtfully, and we'll let you know if we can make the tool behave in a better way.

**Comment by stardustcx** [comment]
OK. It is a wonderful tool that convert much more CNV segments than original liftover. Thanks for your effort and explaination. I think I can close this issue now

**Comment by KyleGao** [comment]
@stardustcx 
We made the following modification:
```
if segment_output_file == None:
    segment_output_file_dynamic = seg_pattern.match(os.path.basename(f)).group(0)
    segment_out_path = os.path.join(output_dir, rel_path, segment_output_file_dynamic)
else:
    segment_out_path = os.path.join(output_dir, rel_path, segment_output_file)
```

It should be able to handle your scenario correctly while still compatible to the old behavor. 
Thank you for identifying the problem and providing a solution!
