### ISSUE TITLE
Converting ponAbe3 and PanTro6 to Hg38

### ISSUE THREAD

**Issue by Sebastian171296** [baudisgroup/segment-liftover#6]
Dear segment-liftover team, 
thank you for doing such a great job!
Our group is currently using your tool for making a comparison of orangutan, chimpanzee and human possible. Segment-liftover had already reduced the coordination loss drastically. Nonetheless, the humanized/lifted files of orangutan and chimpanzee are still containing peaks with their original chromosome names: chr2A and chr2B. These chromosomes are not part of the human genome and the peaks should be relocated somewhere on chr2. Do you have any ideas how I could solve the problem? I run the tool on default. Do you think that the problem is probably caused by the used chain files? 

Kind regards
Sebastian

**Comment by KyleGao** [comment]
Hi Sebastian,
Are you lifting orangutan and chimpanzee genome to human using chain files, or pretending them to be human genome and lifting from one version to another?
You are right of the cause. I think it's because of the chromosome names. The naming convention is  completely inconsistent across different species, so we ignored chromosome with string suffix in names. A workaround solution would be to rename the input chromosome to "chr2" and do the lifting twice for chr2A and chr2B separately. If you are not using cross species chain files, I believe this should work. 
If you are doing from chain files, you have to modify the chromosome name conversion and checking code in the python file. Then just make sure the input chromosome names are exactly as in the chain file.

**Comment by Sebastian171296** [comment]
Thank you for your quick and accurate answer. 
We are using chain files from UCSC to lift both species to human. So, your second solution should help here. 
Do I have to change anything in the UCSC LiftOver algorithm too?

**Comment by KyleGao** [comment]
No, you don't need to change the Liftover. 
I recommend you comment out line 1039 in the python file to keep the tmp directory. Then check both the log files and intermedia files in tmp to confirm where and why the program breaks.
If it failed during the initial lifting, check the code around line 250.
If it failed during the remapping, check the code around line 112.
Direct hard coding chromosome names might be a quick solution.
It may also be because of an unknown bug, sadly we didn't test for all species.
