### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by dKlee99** [baudisgroup/segment-liftover#7]
Hi,
Thanks for making this amazing tool!
I ran the code
`segment_liftover -i ./chm13 -o ./hg38 -c ~/references/t2t-chm13-v1.1.grch38.all.chain -si my.txt -so out.txt`
and got the following error message. 
`object of type 'NoneType' has no len()`
Could you please provide some guidance here? Thank you!

Cheers,
DK

**Comment by KyleGao** [comment]
- My first guess is the input file is not in the expected format, check especially the order the columns.
- Another possible reason is the chromosome names in the input file is different from the chainfile. Because of all the different conventions in different species, there is no syntax checking for chromosome names.

If none of the above solves the problem, could you post the error log so that I can trace it?

**Comment by KyleGao** [comment]
Hi @dKlee99, the error is actually caused by the new version of Click, a package our tool relies on. After specifying an older version (6.7), everything works fine again. You can simply uninstall Click and reinstall Click 6.7.
